# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  containers:
  - container: pg12
    image: postgres:12

trigger:
- master
pr:
- master

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: Build and run unit tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'tests/PgNet.Tests/PgNet.Tests.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/bin/$(BuildConfiguration)/**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
 
- stage: RunIntegrationTests
  displayName: Run integration tests
  jobs:
  - job:
    services:
      postgres: pg12
    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        itemPattern: 'drop/tests/PgNet.IntegrationTests/**'
        targetPath: '$(Pipeline.Workspace)/PgNet.IntegrationTests'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'vstest'
        arguments: '$(Pipeline.Workspace)/**/PgNet.IntegrationTests.dll'



    




